index:
    path: /
    controller: App\Controller\Web\CurrencyController::index
api_v1:
    path:  /api/v1/currency
    controller: App\Controller\Rest\v1\CurrencyController::list
    requirements:
        _method: GET
